plugins {
    id 'java'
    id 'application'
}

group = 'com.silvionetto'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.jgoodies:jgoodies-forms:1.9.0'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'com.silvionetto.Main'
}

test {
    useJUnitPlatform()
}
